### ISSUE TITLE
Vignettes: Broken on CRAN

### ISSUE THREAD

**Issue by discoleo** [mikeblazanin/gcplyr#112]
# PDF Vignettes on CRAN

The "Analyse" vignette (and possibly others) are broken on CRAN. The pdf file (on CRAN) displays garbage text and the code-boxes do NOT display the code.

**Comment by mikeblazanin** [comment]
Hi @discoleo, all the vignette pdf's posted on CRAN look fine on my end. Could you provide more details on what pdf reader you're using?

**Comment by discoleo** [comment]
Vignette on CRAN:
https://cran.r-project.org/web/packages/gcplyr/vignettes/analyze.pdf
	Creation Date: 2/2/2023, 9:24:51 PM
	Modification Date: 2/2/2023, 9:24:51 PM
	Creator: LaTeX via pandoc 

Opened in the pdf-viewer inside the browser: Mozilla Firefox v.109;
- other pdf files on CRAN are displayed correctly;
- the vignettes on GitHub are also displayed correctly;

**Comment by mikeblazanin** [comment]
This appears to be a firefox-specific issue with the CRAN-built vignette pdfs. vignettes look fine on Chrome or when downloaded on my machine too.

Perhaps could be fixed by changing the rbuildignore to ignore the pdf vignette files and instead include the html vignette files. Currently rbuildignore includes both the pdf and the html vignettes. As long as gitignore still doesn't list the pdf files maybe that will work?

**Comment by discoleo** [comment]
When downloading the pdf file from CRAN and opening the downloaded file:
- file is displayed correctly in Microsoft Edge (Windows 10);
- the locally-downloaded pdf is still displayed garbled in Firefox 109 (with the default Firefox pdf viewer);
- could not find any details about the Firefox default pdf viewer;
- however I did not see this issue with many other pdf files on CRAN;

**Comment by mikeblazanin** [comment]
This was an issue on Mozilla's side and has now been fixed by them: https://bugzilla.mozilla.org/show_bug.cgi?id=1816128

Presumably the next release of firefox will include this fix, but it can currently be accessed by using the nightly version of Firefox
